/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jahut9646
 */
public class Jack_H_Adventure extends javax.swing.JFrame {

    /**
     * Creates new form Jack_H_Adventure
     */
    public Jack_H_Adventure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        choice1_button = new javax.swing.JButton();
        choice2_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        main_textarea = new javax.swing.JTextArea();
        start_button = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        choice1_button.setText("Choice 1");
        choice1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice1_buttonActionPerformed(evt);
            }
        });

        choice2_button.setText("Choice 2");
        choice2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice2_buttonActionPerformed(evt);
            }
        });

        main_textarea.setColumns(20);
        main_textarea.setLineWrap(true);
        main_textarea.setRows(5);
        main_textarea.setText("Press start to begin.");
        main_textarea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(main_textarea);

        start_button.setText("Start");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(choice1_button)
                        .addGap(66, 66, 66)
                        .addComponent(start_button)
                        .addGap(77, 77, 77)
                        .addComponent(choice2_button)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choice1_button)
                    .addComponent(start_button)
                    .addComponent(choice2_button))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            int choice;
            
    private void choice1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice1_buttonActionPerformed
        choice = choice + 1;
if (choice == 1)
    {    
            main_textarea.setText("On the island you see a sunny path and a dense covered path.\n" +
                                  "\n" +
                                  "1) The sunny path. \n" +
                                  "\n" +
                                  "2) The dense covered path. ");
    }
else if (choice == 2)
        {
            main_textarea.setText("You see monkeys while walking along. They\n" +
                                  "notice you and start screeching.\n" +
                                  "\n" +
                                  "1) Shoot at the monkeys.\n" +
                                  "\n" +
                                  "2) Run away.");
        }            
else if (choice == 3)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "You shoot at them making them angry so they start pelting you with rocks killing you in the process.\n" +
                                  "\n" +
                                  "Press start to start again.");
            choice = 0;
        }
else if (choice == 102)
        {
            main_textarea.setText("You see a fork in your road. On one side their an old rickety bridge while on the other side their's a tall tree with somthing shiny in it.\n" +
                                  "\n" +
                                  "1) The rickety old bridge\n" +
                                  "\n" +
                                  "2) The tree with somthing shiny in it");
        }
else if (choice == 103)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "while walking across the bridge the ground under you breaks making you fall you your death.\n" +
                                  "\n" +
                                  "Press start to start again.");
            choice = 0;
        }
else if (choice == 101)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "While walking up the mountan it gets too steep and you fall breaking your neck and making you starve to death.\n" +
                                  "\n" +
                                  "Press start to begin again.");
            choice = 0;
        }
else if (choice == 201)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "Even though you stole his stuff you couldn't find his house and froze to death durning your sleep.\n" +
                                  "\n" +
                                  "Press start to begin again.");
            choice = 0;
        }
else if (choice == 301)
        {
            main_textarea.setText("You kill him and find supplies to help you survive on this island. You decide to leave and look for the treasure.\n" +
                                  "\n" +
                                  "1) You chose to go up the mountan.\n" +
                                  "\n" +
                                  "2) You walk around the base of the mountan looking for treasure.");
            
        }
else if (choice == 302)
        {
            main_textarea.setText("While climbing the mountan you see get hungry.\n" +
                                  "\n" +
                                  "1) Eat the soup you stole from the old man.\n" +
                                  "\n" +
                                  "2) Eat the weird mushroom that are growing on the cliff.");
            
        }
else if (choice == 303)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "After eating the soup you fall unconsius and fall down the mountan dying from the fall.\n" +
                                  "\n" +
                                  "Press start to begin again.");
            choice = 0;
        }
else if (choice == 403)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "You froze to death while searching the cave." +
                                  "\n" +
                                  "Press start to start again.");
            choice = 0;
        }
else
        {
            choice = 0;
        }
             // TODO add your handling code here:
    }//GEN-LAST:event_choice1_buttonActionPerformed

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
if (choice == 0)
            {
            main_textarea.setText("You are a pirate their are two islands\n" +
                                  "and one of them has treasure on it.\n" +
                                  "\n" +
                                  "1) First island has a lushious jungle\n" +
                                  "\n" +
                                  "2) Second island has a giant mountan that\n" +
                                  " reaches the clouds. ");
            }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_start_buttonActionPerformed

    private void choice2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice2_buttonActionPerformed
        choice = choice + 100;
if (choice == 102)
        {
            main_textarea.setText("YOU DIED\n" +
                                  "\n" +
                                  "While running away you don't look where your going and hit a tree making a coconut fall on your head.\n" +
                                  "\n" +
                                  "Press start to start again.");
            choice = 0;
        }
else if (choice == 101)
        {
            main_textarea.setText("while walking along the path you see a waterfall.\n" +
                                  "\n" +
                                  "1) Ignore it an keep going along the path.\n" +
                                  "\n" +
                                  "2) Go into the water fall to fing tresure.");
        }    
else if (choice == 201)    
        {
          main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "While trying to go through the water fall you get swept under and drown to death.\n" +
                                  "\n" +
                                  "Press start to start again.");
          choice = 0;
        }
else if (choice == 202)    
        {
          main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "While climbing up the tree you lose you grip and fall to your death.\n" +
                                  "\n" +
                                  "Press start to start again.");
          choice = 0;
        }
else if (choice == 100)
        {
            main_textarea.setText("While walking around the island you see two paths.\n" +
                                  "\n" +
                                  "1) You take the bumpy path towards the mountain.\n" +
                                  "\n" +
                                  "2) You walk along the paved path.");
        }
else if (choice == 200)
        {
            main_textarea.setText("While walking across the path you see an old man and he offers you to stay in his house.\n" +
                                  "\n" +
                                  "1) Kill him and steal his stuff.\n" +
                                  "\n" +
                                  "2) Follow him to his house.");
        }
else if (choice == 300)
        {
            main_textarea.setText("You follow him to his home and he offers you some soup.\n" +
                                  "\n" +
                                   "1) Kill him and steal his stuff.\n" +
                                  "\n" +
                                  "2) Drink the soud and listen to his lifes story.");
        }
else if (choice == 400)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "He put somthing in the soup and you fall unconcus when you wake up your strapped to a table and he's eating you." +
                                  "\n" +
                                  "Press start to try again.");
            choice = 0;
        }
else if (choice == 402)
        {
            main_textarea.setText("You feel weird after eating the mushrooms, but you remain focused and you climb up the mountan. when it wears off you see a icy cave.\n" +
                                  "\n" +
                                  "1) Icy cave.\n" +
                                  "\n" +
                                  "2) Keep heading up the mountan.");    
        }
else if (choice == 502)
        {
            main_textarea.setText("CONGRADULATIONS!\n" +
                                  "\n" +
                                  "You reach the top and find the one piece making you the strongest pirate to ever live.\n" +
                                  "\n" +
                                  "Press start to find the other endings.");
            choice = 0;   
        }
else if (choice == 401)
        {
            main_textarea.setText("YOU DIED.\n" +
                                  "\n" +
                                  "You get mauled to death by a pack of wolfs.\n" +
                                  "\n" +
                                  "Press start to try again.");
            choice = 0;   
        }
else
        {
            choice = 0;
        }        
        
// TODO add your handling code here:
    }//GEN-LAST:event_choice2_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jack_H_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jack_H_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jack_H_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jack_H_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jack_H_Adventure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choice1_button;
    private javax.swing.JButton choice2_button;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea main_textarea;
    private javax.swing.JButton start_button;
    // End of variables declaration//GEN-END:variables
}
